c

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -62,8 +62,12 @@ jobs:
       - name: Build with Next.js
         run: pnpm next build
 
-      - name: Debug Output Directory
-        run: ls -la
+      - name: Debug `out` folder
+        run: |
+          echo "Contents of root directory:"
+          ls -la
+          echo "Contents of ./out directory:"
+          ls -la ./out || echo "'out' folder not found"
 
       # - name: Run postbuild script
       #   run: pnpm node lib/buildTools/prefixFonts.js
